#!/bin/bash

currentuser=$(/usr/bin/who | awk '/console/{ print $1 }')
/usr/bin/osascript > /dev/null << EOT

        tell application "Finder" 
        activate
        mount volume "smb://example.com/networkshares/Home%20Directories/${currentuser}/"
        end tell

EOT

AppleScript

set userName to do shell script "whoami"

mount volume "smb://example.com/networkshares/Home%20Directories/" & userName
